# Importing Libraries 

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report

# Importing Train Dataset 

In [23]:
train_dataset = pd.read_csv("train.csv")
train_dataset

employee_id         department     region         education gender  \
0            65438  Sales & Marketing   region_7  Master's & above      f   
1            65141         Operations  region_22        Bachelor's      m   
2             7513  Sales & Marketing  region_19        Bachelor's      m   
3             2542  Sales & Marketing  region_23        Bachelor's      m   
4            48945         Technology  region_26        Bachelor's      m   
5            58896          Analytics   region_2        Bachelor's      m   
6            20379         Operations  region_20        Bachelor's      f   
7            16290         Operations  region_34  Master's & above      m   
8            73202          Analytics  region_20        Bachelor's      m   
9            28911  Sales & Marketing   region_1  Master's & above      m   
10           29934         Technology  region_23               NaN      m   
11           49017  Sales & Marketing   region_7        Bachelor's      f   
12           60051  Sales & Marketing   region_4        Bachelor's      m   
13           38401         Technology  region_29  Master's & above      m   
14           77040                R&D   region_2  Master's & above      m   
15           43931         Operations   region_7        Bachelor's      m   
16            7152         Technology   region_2        Bachelor's      m   
17            9403  Sales & Marketing  region_31        Bachelor's      m   
18           17436  Sales & Marketing  region_31        Bachelor's      m   
19           54461         Operations  region_15        Bachelor's      m   
20           12067        Procurement  region_14        Bachelor's      m   
21           33332         Operations  region_15               NaN      m   
22           58789            Finance  region_11        Bachelor's      f   
23           71177        Procurement   region_5        Bachelor's      m   
24           52057            Finance  region_22  Master's & above      m   
25           26585         Technology  region_22        Bachelor's      m   
26           37749        Procurement  region_26        Bachelor's      m   
27            2370         Technology  region_26        Bachelor's      m   
28            8219          Analytics   region_5        Bachelor's      m   
29           74759  Sales & Marketing   region_4        Bachelor's      m   
...            ...                ...        ...               ...    ...   
54778        30691        Procurement   region_2        Bachelor's      f   
54779        49923         Technology  region_30        Bachelor's      f   
54780        73767         Operations  region_19        Bachelor's      f   
54781        76497                 HR  region_27        Bachelor's      f   
54782        17281         Operations   region_2   Below Secondary      m   
54783        45504        Procurement   region_2   Below Secondary      m   
54784        68370  Sales & Marketing  region_30        Bachelor's      m   
54785        42055         Technology  region_26        Bachelor's      m   
54786        32291  Sales & Marketing  region_31        Bachelor's      f   
54787        77455         Technology  region_27        Bachelor's      m   
54788        75164  Sales & Marketing  region_13        Bachelor's      f   
54789        75942  Sales & Marketing   region_7  Master's & above      m   
54790        67988                 HR   region_2        Bachelor's      f   
54791        27274         Technology  region_11        Bachelor's      m   
54792          994  Sales & Marketing  region_14        Bachelor's      m   
54793        28400         Technology   region_2        Bachelor's      m   
54794        35000         Operations  region_16        Bachelor's      m   
54795        13477        Procurement  region_15  Master's & above      m   
54796        12592  Sales & Marketing  region_25  Master's & above      m   
54797        62450  Sales & Marketing  region_11        Bachelor's      m   
547

# Data pre-processing

In [24]:
#Filling the missing data with MODE
train_dataset = train_dataset.fillna(train_dataset.mode().iloc[0])
HR_dataset = train_dataset.iloc[:,6:13].values
HR_predict = train_dataset.iloc[:,13].values
HR_predict

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Applying Logistic Regression

In [25]:
LogReg = LogisticRegression()
LogReg.fit(HR_dataset,HR_predict)
print (LogReg.score(HR_dataset, HR_predict))

C:\Users\Achal94\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.9164538023646183


# Evaluating model on Train Data

In [26]:
y_pred = LogReg.predict(HR_dataset)
print(classification_report(HR_predict,y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     50140
           1       0.59      0.06      0.11      4668

   micro avg       0.92      0.92      0.92     54808
   macro avg       0.76      0.53      0.53     54808
weighted avg       0.89      0.92      0.88     54808



# Importing Test Data

In [27]:
test_dataset = pd.read_csv('test.csv')
test_dataset

employee_id         department     region         education gender  \
0             8724         Technology  region_26        Bachelor's      m   
1            74430                 HR   region_4        Bachelor's      f   
2            72255  Sales & Marketing  region_13        Bachelor's      m   
3            38562        Procurement   region_2        Bachelor's      f   
4            64486            Finance  region_29        Bachelor's      m   
5            46232        Procurement   region_7        Bachelor's      m   
6            54542            Finance   region_2        Bachelor's      m   
7            67269          Analytics  region_22        Bachelor's      m   
8            66174         Technology   region_7  Master's & above      m   
9            76303         Technology  region_22        Bachelor's      m   
10           60245  Sales & Marketing  region_16        Bachelor's      m   
11           42639  Sales & Marketing  region_17  Master's & above      m   
12           30963  Sales & Marketing   region_4  Master's & above      f   
13           54055          Analytics  region_24        Bachelor's      m   
14           42996         Operations  region_11        Bachelor's      m   
15           12737  Sales & Marketing   region_7        Bachelor's      m   
16           27561         Operations  region_27        Bachelor's      f   
17           26622  Sales & Marketing  region_17        Bachelor's      m   
18           31582        Procurement   region_7        Bachelor's      f   
19           29793        Procurement  region_27        Bachelor's      m   
20           72735  Sales & Marketing   region_9  Master's & above      m   
21            5677         Technology  region_17        Bachelor's      m   
22           60889         Technology  region_29  Master's & above      m   
23           51498        Procurement   region_4  Master's & above      m   
24            8566            Finance  region_20        Bachelor's      f   
25           53151         Operations  region_20        Bachelor's      m   
26           16203  Sales & Marketing  region_17  Master's & above      m   
27           61083          Analytics  region_13        Bachelor's      m   
28           74849         Operations  region_22        Bachelor's      m   
29           13259  Sales & Marketing  region_34        Bachelor's      m   
...            ...                ...        ...               ...    ...   
23460        72190         Operations  region_32        Bachelor's      f   
23461        27155  Sales & Marketing  region_22        Bachelor's      f   
23462        15959          Analytics  region_31        Bachelor's      m   
23463        72900          Analytics  region_21        Bachelor's      m   
23464        57683          Analytics   region_2        Bachelor's      m   
23465        55174         Technology   region_7        Bachelor's      f   
23466        51115         Technology   region_2  Master's & above      f   
23467        50134         Technology   region_2        Bachelor's      m   
23468        59775  Sales & Marketing   region_2        Bachelor's      m   
23469        14408        Procurement  region_26        Bachelor's      f   
23470         4351  Sales & Marketing  region_30        Bachelor's      m   
23471        59625        Procurement  region_13  Master's & above      m   
23472        29379         Technology   region_6        Bachelor's      f   
23473        67979         Operations  region_25  Master's & above      m   
23474        61451         Operations   region_7  Master's & above      f   
23475        73871              Legal  region_27        Bachelor's      f   
23476        52090  Sales & Marketing   region_2  Master's & above      f   
23477        18488        Procurement   region_2        Bachelor's      m   
23478        59673        Procurement  region_17        Bachelor's      f   
23479        39410  Sales & Marketing   region_2        Bachelor's      m   
234

In [28]:
test_dataset = test_dataset.fillna(test_dataset.mode().iloc[0])
HR_dataset = test_dataset.iloc[:,6:13].values
HR_dataset

array([[ 1., 24.,  3., ...,  1.,  0., 77.],
       [ 1., 31.,  3., ...,  0.,  0., 51.],
       [ 1., 31.,  1., ...,  0.,  0., 47.],
       ...,
       [ 1., 26.,  4., ...,  0.,  0., 50.],
       [ 3., 27.,  3., ...,  0.,  0., 70.],
       [ 3., 40.,  5., ...,  1.,  0., 89.]])

In [29]:
print(len(HR_dataset))

23490


In [30]:
test_pred = LogReg.predict(HR_dataset)
test_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Importing Sample Submission

In [31]:
sample_dataset= pd.read_csv("sample_submission_M0L0uXE.csv")

In [32]:
y_true=sample_dataset.iloc[:,1].values
y_true

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Calculating F1 score

In [34]:
f1_score(y_true,test_pred,average='weighted')

C:\Users\Achal94\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


0.9955958438448711